formatter: "markdown table"

version: ""

header-from: "main.tf"

sections:
  hide: []
  show: ["header", "inputs", "outputs"]

output:
  file: "README.md"
  mode: "inject"

settings:
  anchor: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
